### ISSUE TITLE
0.1.0 RC3 - Bugs

### ISSUE THREAD

**Issue by Yuniac** [TheMadDodger/Glory#180]

**Comment by Yuniac** [comment]
* The select project path when creating a new project is buggy. 
* The window visually is buggy and I don't understand whether this is a path to save the project or to import one.
![image](https://user-images.githubusercontent.com/76709894/236678553-2023b97e-2dd7-4793-bb30-6de091f3b058.png)
* Clicking on the desktop, for example, shows no files (even when I select all files types from the picker)
![image](https://user-images.githubusercontent.com/76709894/236678565-75f4aa17-a093-4861-b41f-445d063c3165.png)
* The default path could be something simpler than nested documents, for me it defaulted to one drive and I don't use it. A better path maybe would be just `/desktop/glory` or so.

**Comment by Yuniac** [comment]
* Cant attach a script to the empty object step in the tutorial: 

![image](https://user-images.githubusercontent.com/76709894/236680213-5a8eb42d-22b1-4c35-8275-412ba4115f2d.png)

The tutorial isn't clear enough to me on how or where I can attach the script to the newly created object

**Comment by TheMadDodger** [comment]
> * Cant attach a script to the empty object step in the tutorial:
> 
> ![image](https://user-images.githubusercontent.com/76709894/236680213-5a8eb42d-22b1-4c35-8275-412ba4115f2d.png)
> 
> The tutorial isn't clear enough to me on how or where I can attach the script to the newly created object

Good point
Did you figure out how? It needs to be selected in the Script property.

**Comment by TheMadDodger** [comment]
> 

Replacing this with the file dialog of the operating system, which will resolve all these issues
